name: tests
run-name: tests
on:
  workflow_call:

  push:
    branches:
      - "**"
jobs:
  python-unittests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python_version: ['3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - run: pip install -r requirements.txt
      - run: tox

  cpp-unittests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python_version: ['3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: 'Install dependencies'
        run: sudo bash scripts/install_dependencies_debian_ubuntu.sh
      - name: 'Build'
        run: |
          mkdir tests/cpp/build/
          cd tests/cpp/build/
          cmake ..
          make -j3
      - name: 'Run tests'
        run: |
          cd tests/cpp/build/
          ./cpp_unit_tests